# Generated by Django 5.0.2 on 2024-03-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finch',
            old_name='breed',
            new_name='gender',
        ),
    ]
