# Generated by Django 5.0.2 on 2024-03-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_feeding_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
