# Generated by Django 5.0.2 on 2024-03-13 03:57

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_feeding_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='date',
            field=models.DateField(validators=[main_app.models.validate_date], verbose_name='feeding date'),
        ),
    ]
